apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-kubernetes
    labels:
        app: nodejs-kubernetes-api
spec:
    selector:
        matchLabels:
            name: nodejs-kubernetes-api
    template:
        metadata:
            labels:
                name: nodejs-kubernetes-api
        spec:
            containers:
                - name: nodejs-kubernetes-api
                  image: dannysofftie/nodejs-kubernetes-api
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5000
                        protocol: TCP
                  resources:
                      requests:
                          memory: 100Mi
                          cpu: 50m
                      limits:
                          memory: 300Mi
                          cpu: 100m
                  env:
                      - name: NODE_ENV
                        value: 'Kubernetes'
    replicas: 4
