apiVersion: v1
kind: Service
metadata:
    name: nodejs-kubernetes-api
spec:
    type: LoadBalancer
    selector:
        name: nodejs-kubernetes-api
    ports:
        - name: http
          port: 4000
          targetPort: 5000
